import { notFound, redirect } from 'next/navigation';
import { Container } from '@/components/ui/primitives';
import { ActiveAwareSidebar } from '@/components/learn/active-aware-sidebar';
import { getCourseBySlug } from '@/lib/api/public';
import { getCourseProgress } from '@/lib/api/learn';
import { requireRole } from '@/lib/guards';
import { ROLES } from '@/lib/types';

/**
 * The course player shell.
 *
 * The sidebar lives in the layout so it survives navigation between lessons: moving from
 * one lesson to the next re-renders only the page slot, leaving the contents rail mounted.
 *
 * Three checks run before anything renders, cheapest first:
 *   1. `requireRole` - only students take courses. Staff preview through the public pages.
 *   2. the course must exist.
 *   3. `getCourseProgress` returns null when the backend refuses the request, which is
 *      exactly what happens for a student who is not enrolled. The enrollment gate is
 *      therefore the backend's answer, not a rule re-implemented here.
 */
// `LayoutProps` is generated by Next from the route tree and is globally available, so
// the params type stays in step with the folder structure instead of being hand-written.
export default async function LearnLayout({ children, params }: LayoutProps<'/learn/[slug]'>) {
  const { slug } = await params;

  await requireRole([ROLES.STUDENT]);

  const course = await getCourseBySlug(slug);

  if (!course) {
    notFound();
  }

  const progress = await getCourseProgress(course.documentId);

  if (!progress) {
    // Not enrolled. The course page is where the enroll button lives.
    redirect(`/courses/${slug}`);
  }

  const lessons = [...(course.lessons ?? [])].sort((a, b) => a.order - b.order);
  const quiz = course.quizzes?.[0] ?? null;

  return (
    <div className="border-t border-line">
      <Container className="grid gap-10 py-10 lg:grid-cols-12 lg:gap-12">
        {/* Sticky on desktop only. On mobile a sticky rail would eat most of the screen,
            so the contents sit above the lesson as a normal block. `top-24` clears the
            64px header. */}
        <aside className="lg:col-span-4 xl:col-span-3">
          <div className="lg:sticky lg:top-24">
            <ActiveAwareSidebar
              slug={slug}
              title={course.title}
              lessons={lessons}
              quiz={quiz}
              completedLessonIds={progress.completedLessonIds}
              percentage={progress.percentage}
            />
          </div>
        </aside>

        <div className="lg:col-span-8 xl:col-span-9">{children}</div>
      </Container>
    </div>
  );
}
